FROM eclipse-temurin:21-jdk AS build

WORKDIR /app

COPY . .



FROM eclipse-temurin:21-jre

WORKDIR /app

COPY --from=build /app/target/*.jar app.jar

EXPOSE 9093

ENTRYPOINT ["java", "-jar", "app.jar"]